ARG SWIFT_VERSION=4.2

FROM ibmcom/swift-ubuntu:${SWIFT_VERSION}
WORKDIR /app

COPY Package.swift .
COPY Package.resolved .
RUN swift package resolve

COPY . .
RUN swift build -c release

FROM ibmcom/swift-ubuntu-runtime:${SWIFT_VERSION}
WORKDIR /app

COPY --from=0 /app/.build/x86_64-unknown-linux/release/Run .

CMD ./Run --env production --hostname 0.0.0.0 --port $PORT
